### ISSUE TITLE
UserOnline cannot be found in namespace

### ISSUE THREAD

**Issue by ram2141** [forcePanda/blogfp#1]
Hello @forcePanda 
First I would say thank you for such a nice project and sharing it. 

When I deploy the code it gives me this below error. Can you please help me to resolve it? 

![image](https://user-images.githubusercontent.com/31553388/111010147-780f0180-834a-11eb-8f4d-ffd2d9a48b40.png)

Thanks in advance.

**Comment by forcePanda** [comment]
Ahh, I didn't add the static resource! 😅
Added now. :)

**Comment by ram2141** [comment]
> Ahh, I didn't add the static resource! 😅
> Added now. :)

Thank You for your prompt reply. I got it to work by just adding online image link in .cmp file. For some reason, I am not able to deploy it on production ☹️.

**Comment by forcePanda** [comment]
You need to write test class for the controller! :)

**Comment by ram2141** [comment]
> You need to write test class for the controller! :)

Sorry, I am new to this and asking you too many questions. 

When I deploy this code to org via Ctl +Shift +P using Salesforce CLI, I get this below error. 

![image](https://user-images.githubusercontent.com/31553388/111197636-ee467a80-857b-11eb-9317-6e81fe401187.png)

Also, I have tried with terminal using this below code and getting below error.

sfdx force:source:deploy -u nmp -p force-app -l RunLocalTests -w 100

![image](https://user-images.githubusercontent.com/31553388/111197939-4a110380-857c-11eb-98a9-b5ac706c731c.png)

I'll be greatly appreciated if you could give me the solution  for this to deploy on production.

Thanks in advance :)

**Comment by forcePanda** [comment]
Like I said, you need to write Apex tests for the ChatComponentController class with a code coverage of 75% or higher to successfully deploy it.

**Comment by ram2141** [comment]
> Like I said, you need to write Apex tests for the ChatComponentController class with a code coverage of 75% or higher to successfully deploy it.

Thank you for reply. Yes, It makes sense. Do you have file for apex tests for the ChatComponentController? I have been trying but couldn't figure it out. If you could share here that would be greatly appreciated.

**Comment by forcePanda** [comment]
Unfortunately, I do not. :(
The dev org where I originally built this component got expired. 😅

**Comment by ram2141** [comment]
No worries, It's all good. Well.... thank you so much for your time and helping me with this issue.
